repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude_types:
    - svg
  - id: check-yaml
  - id: check-added-large-files
    args:
    - --maxkb=1000

    # Lint and format Python code
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
    -   id: ruff-check
        # args: [--statistics]
        args: [--fix, --show-fixes, --unsafe-fixes]
    -   id: ruff-format
        # args: [--diff]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.19.1
  hooks:
  - id: mypy
    additional_dependencies:
    - pandas-stubs
    - types-tqdm
    - types-Jinja2
    args:
    - --config-file=pyproject.toml
    exclude: |
            (?x)^(
                tests/.*
            )$


- repo: https://github.com/codespell-project/codespell
  rev: v2.4.2
  hooks:
  - id: codespell
    additional_dependencies:
    - tomli
    args:
    - --skip=*.svg
    exclude: paper/.*

- repo: https://github.com/hadolint/hadolint
  rev: v2.14.0
  hooks:
  - id: hadolint-docker
    name: Lint Dockerfiles
    description: Runs hadolint Docker image to lint Dockerfiles
    language: docker_image
    types:
    - dockerfile
    entry: ghcr.io/hadolint/hadolint hadolint

ci:
  autoupdate_commit_msg: 'chore: update pre-commit hooks'
  autoupdate_schedule: quarterly
  autofix_commit_msg: 'style: pre-commit fixes'
  autofix_prs: false
  skip:
  - hadolint-docker
