;  See https://tox.wiki/en
[tox]
requires =
    tox>=4
    tox-uv
; run lint by default when just calling "tox"
env_list = lint

[global_var]
passenv =
    CI
    USERNAME
    # Pass user color preferences through
    PY_COLORS
    FORCE_COLOR
    NO_COLOR
    CLICOLOR
    CLICOLOR_FORCE


[testenv:test]
description = install test data
passenv = {[global_var]passenv}
extras = test
commands =
    pytest --cov=giga_connectome --cov-report=xml {posargs:}

[testenv:test_no_smoke]
description = install test data
passenv = {[global_var]passenv}
extras = test
commands =
    pytest -m "not smoke" --cov=giga_connectome --cov-report=xml {posargs:}


[testenv:test_data]
description = install test data
skip_install = true
allowlist_externals =
    mkdir
    wget
    tar
    rm
commands =
    mkdir tests/data/test_data
    wget --retry-connrefused \
        --waitretry=5 \
        --read-timeout=20 \
        --timeout=15 \
        -t 0 \
        -q \
        -O tests/ds000017.tar.gz \
        "https://zenodo.org/record/8091903/files/ds000017-fmriprep22.0.1-downsampled-nosurface.tar.gz?download=1"
    tar -xzf tests/ds000017.tar.gz -C tests/data/test_data/
    rm tests/ds000017.tar.gz
